### ISSUE TITLE
Crash on project files with source name of (null)

### ISSUE THREAD

**Issue by matto1990** [simonwagner/mergepbx#10]
I encountered an unmergeable project file. For some reason XCode created a few lines in the project file that looked like:

```
9F7A68181A24D72800A23C41 /* (null) in Sources */ = {isa = PBXBuildFile; };
```

Removing lines like that from the project file caused mergepbx to work perfectly again! I have no idea at all why it would be doing that, but it happened when I added a file into my project. I am using Xcode 6.1.1.

I can send you the project file dumps but I'd prefer to do this via email rather than through Github if that's ok.

Thanks again for the brilliant project!

**Comment by simonwagner** [comment]
Yeah, send me the project file via e-mail, I will have a look at it.

**Comment by simonwagner** [comment]
Your problem should be fixed now. I tested it with your files and it no longer crashes.

**Comment by matto1990** [comment]
Perfect! Works for me too.

Thanks again!
