### ISSUE TITLE
merging failed: strategy not found: PBXHeadersBuildPhaseMerger3

### ISSUE THREAD

**Issue by ncalexan** [simonwagner/mergepbx#11]
I'm seeing consistent merge failures with Mozilla's Firefox for iOS Swift project at https://github.com/mozilla/firefox-ios.  The error log (snippet) is below.

Merge failure would not be a huge deal except that my configuration doesn't fall back to manual; it obliterates the change entirely.  (I think this is an issue with my configuration, not necessarily with mergebpx.)

A quick skim of the code suggests that the project section corresponding to the Swift "bridging header" needs to be explicitly handled, somehow, in mergepbx.  I will try to figure out what needs to be done but would appreciate direction.

```
Applying: Bug 1141843 - Final: project changes for Sync working branch.
Using index info to reconstruct a base tree...
M	Client.xcodeproj/project.pbxproj
Falling back to patching base and 3-way merge...
merging failed: strategy not found: PBXHeadersBuildPhaseMerger3
Auto-merging Client.xcodeproj/project.pbxproj
CONFLICT (content): Merge conflict in Client.xcodeproj/project.pbxproj
Failed to merge in the changes.
Patch failed at 0014 Bug 1141843 - Final: project changes for Sync working branch.
The copy of the patch that failed is found in:
   /Users/nalexander/Mozilla/firefox-ios/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by simonwagner** [comment]
Could you try again with the latest version on master?

**Comment by simonwagner** [comment]
I have merged your pull request and fixed some bugs in the code. I also have enabled `--clean` per default, which should fix the `KeyError`. Can you tell me if everything works now for you?
