### ISSUE TITLE
merging failed: 'fileRef'

### ISSUE THREAD

**Issue by bpenda** [simonwagner/mergepbx#21]
mergepbx just sits there for a while and then I get merging failed: 'fileRef'. 
[mbpxdump.zip](https://github.com/simonwagner/mergepbx/files/335932/mbpxdump.zip)

**Comment by simonwagner** [comment]
Could you try out v0.10? This should be fixed now.

An entry in your project file was broken (the one with the id `3E84E0A1885C1FB27F6AC15087464E24`), which led to the crash, as it was missing its `fileRef` attribute. `mergepbx` now skips those entries in the clean up phase.

**Comment by AnLuoRidge** [comment]
I have tried v0.10. The " merging failed: 'fileRef' " warning never appear! Thank you!
